// This file is automatically generated by JELLOG framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using DataGap.Jellog.Application.Dtos;
using DataGap.Jellog.Http.Client;
using DataGap.Jellog.Http.Modeling;
using DataGap.Jellog.DependencyInjection;
using DataGap.Jellog.Http.Client.ClientProxying;
using DataGap.CmsKit.Public.Contact;

// ReSharper disable once CheckNamespace
namespace DataGap.CmsKit.Public.Contact.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContactPublicAppService), typeof(ContactPublicClientProxy))]
public partial class ContactPublicClientProxy : ClientProxyBase<IContactPublicAppService>, IContactPublicAppService
{
    public virtual async Task SendMessageAsync(ContactCreateInput input)
    {
        await RequestAsync(nameof(SendMessageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ContactCreateInput), input }
        });
    }
}
