// This file is automatically generated by JELLOG framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using DataGap.Jellog.Application.Dtos;
using DataGap.Jellog.Http.Client;
using DataGap.Jellog.Http.Modeling;
using DataGap.Jellog.DependencyInjection;
using DataGap.Jellog.Http.Client.ClientProxying;
using DataGap.CmsKit.Public.UrlShorting;

// ReSharper disable once CheckNamespace
namespace DataGap.CmsKit.Public.UrlShorting.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUrlShortingPublicAppService), typeof(UrlShortingPublicClientProxy))]
public partial class UrlShortingPublicClientProxy : ClientProxyBase<IUrlShortingPublicAppService>, IUrlShortingPublicAppService
{
    public virtual async Task<ShortenedUrlDto> FindBySourceAsync(string source)
    {
        return await RequestAsync<ShortenedUrlDto>(nameof(FindBySourceAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), source }
        });
    }
}
