// This file is automatically generated by JELLOG framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using DataGap.Jellog.Application.Dtos;
using DataGap.Jellog.Http.Client;
using DataGap.Jellog.Http.Modeling;
using DataGap.Jellog.DependencyInjection;
using DataGap.Jellog.Http.Client.ClientProxying;
using DataGap.CmsKit.Admin.Contact;

// ReSharper disable once CheckNamespace
namespace DataGap.CmsKit.Admin.Contact.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContactSettingsAppService), typeof(ContactSettingClientProxy))]
public partial class ContactSettingClientProxy : ClientProxyBase<IContactSettingsAppService>, IContactSettingsAppService
{
    public virtual async Task<CmsKitContactSettingDto> GetAsync()
    {
        return await RequestAsync<CmsKitContactSettingDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(UpdateCmsKitContactSettingDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateCmsKitContactSettingDto), input }
        });
    }
}
